[GOOGLE_SHEETS]
type = "service_account"
project_id = "asset-database-477316"
private_key_id = "11a674455145b27f0c42026e6beee7481a50c751"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDd6ZRxQmhaVknb
JBDGfL76r8ps4+sWard+CZRVwmMbFdJwHOaP/OWtsZb6wu6zqTk6iVLpwgUlv0SD
mfWpC5QjWpTFD8BH2jDg4JZd8voXDtah2sFKic2VilEdre0JKR1Iqyp5Os2rwWJA
4hQcRoTd2wj8oz8mXTXA7EdY4DeXdjhsDxunfpZojdxIqwVFzUJyc3uEwiXSaMFN
P4JrozvYIEIgbwddAxzgPxWTk9mbMQrWUBivAKGphC/1nlnKAsqHBw3LDafH/XfV
RYGDoZXos/33sTKhzXNsUTk0u3vMfyRGJppB32XmtgOwXRWYDjhDgdT/zm9YAWyU
G5H2AsQnAgMBAAECggEAOiFXXMngCxYCd9C9QjloT8Pf22Fi8jbXRUFeJY7rpisz
umGftgUx5yuXmK2amN6R2rchTJGiBo7RdEXO187sKcyvHuXu4QOTfTzntsmQ4Jxm
9fQXYR6zB2K5t/QZHSazgJcx45rXSJA6XDO8v+FrKbCYbJGY18Rf8d8TG4F0noyA
6X0nHA7fpvlhA2YfMRViPevxMGx1Qkx/3GSntivYBjAwZeK9BQ3zXowhKzZotgsN
VGsyYarbtn4JZHRRU3VqalnGWaaVSgIwYb8qlhi45SvTaNfcjstOWb12F6z8+CiK
d0veD8flO23tGVH1/3A1gw1h1HHBn0uBsLHQ/XJZkQKBgQD3naN7ze6HKM6a16Qm
p2sKTFy5XiSb9T8GrEW27f6s5I8B8tQj5KuTSv8KKbK/dN5zhu5EzsTxgQrwXpH1
FRXHoj3knpqg1W1G4zJFg1GxrVh5Cf78aQy67quDLoCrkoeHrbrq8RkU8S2v2AJj
OJX5HPv2UNZgdOSv2NVjunAqUQKBgQDlbSRE/vgvq3SMFhl6cehmMTINj/Np1je4
sR4eY3yL/5c06yXryVvVTFal1gql2FZA+mQxtB7ErdlwdsLSRI255V85RaqVEknk
BB4o6uLz6c75Mazpf2Zjwr6Qb9WoB3ucJoTC5IPS6z2vgylml5hSqo/ZAS83XV97
rOYjRL7w9wKBgCFBmM1t8RVSE72ULMXMQoIVk3aKAFy56YcZ6BsTh9rsr5BRbtCL
S8fykKJqy0kPhzj47FNteeH9tNxnty61cEFptupXqujjAVQ9+2h+pKA6aeGHyCla
ao1ItNxfiISCn5VHbg1T6Ex5v+sYFeoBlZLpo6WHYeN+j6BWfQJx7dKhAoGBAIaH
ahYfIC7rrcqbBtOayXhq7nuvZj8wQrpE+XE+SwDYnbSFElZhWz0Gp2RUzyeSZHlz
mZ7fjI8tlevxZ6neUvCnhB/ULwN8luFiXMEHgo8eEaRjsY21i7eBsTaGrVT7Fkto
9r5FOttJ34D0OymSSNpoczL/E822LdAagVQ68m/fAoGAUCgd4w59xxKabNC0+ZGx
uMpuqvltTfRI+5PopmHcQGA5LHwdiE7e00Zo1OQDhqIyTojOJ+qTJOIFDbhZ2kZz
IoDO/dFAQddEs/kXDLB40zlSAkybknaCOeWT8xikiaMweF2JEUaFHJKkWdsfIvwH
vsBWEbxHU0SOBdAeib0N16A=
-----END PRIVATE KEY-----
"""
client_email = "asset-database@asset-database-477316.iam.gserviceaccount.com"
client_id = "104377012575525405476"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/asset-database%40asset-database-477316.iam.gserviceaccount.com"

GOOGLE_SHEET_ID = "1q9jfezVWpFYAmvjo81Lk788kf9DNwqvSx7yxHWRGkec"
